In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Ames_House_Sales_Cropped.csv')
df

BldgType CentralAir  1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  \
0        1Fam          Y     856.0     854.0        0.0             3   
1        1Fam          Y    1262.0       0.0        0.0             3   
2        1Fam          Y     920.0     866.0        0.0             3   
3        1Fam          Y     961.0     756.0        0.0             3   
4        1Fam          Y    1145.0    1053.0        0.0             4   
5        1Fam          Y     796.0     566.0      320.0             1   
6        1Fam          Y    1694.0       0.0        0.0             3   
7        1Fam          Y    1107.0     983.0        0.0             3   
8        1Fam          Y    1022.0     752.0        0.0             2   
9      2fmCon          Y    1077.0       0.0        0.0             2   
10       1Fam          Y    1040.0       0.0        0.0             3   
11       1Fam          Y    1182.0    1142.0        0.0             4   
12       1Fam          Y     912.0       0.0        0.0             2   
13       1Fam          Y    1494.0       0.0        0.0             3   
14       1Fam          Y    1253.0       0.0        0.0             2   
15       1Fam          Y     854.0       0.0        0.0             2   
16       1Fam          Y    1004.0       0.0        0.0             2   
17     Duplex          Y    1296.0       0.0        0.0             2   
18       1Fam          Y    1114.0       0.0        0.0             3   
19       1Fam          Y    1339.0       0.0        0.0             3   
20       1Fam          Y    1158.0    1218.0        0.0             4   
21       1Fam          Y    1108.0       0.0        0.0             3   
22       1Fam          Y    1795.0       0.0        0.0             3   
23     TwnhsE          Y    1060.0       0.0        0.0             3   
24       1Fam          Y    1060.0       0.0        0.0             3   
25       1Fam          Y    1600.0       0.0        0.0             3   
26       1Fam          Y     900.0       0.0        0.0             3   
27       1Fam          Y    1704.0       0.0        0.0             3   
28       1Fam          Y    1600.0       0.0        0.0             2   
29       1Fam          N     520.0       0.0        0.0             1   
...       ...        ...       ...       ...        ...           ...   
1349     1Fam          Y    1048.0     510.0        0.0             3   
1350     1Fam          Y     804.0       0.0        0.0             2   
1351     1Fam          Y    1440.0       0.0        0.0             3   
1352     1Fam          Y     734.0    1104.0        0.0             4   
1353   TwnhsE          Y     958.0       0.0        0.0             2   
1354     1Fam          Y     968.0       0.0        0.0             4   
1355     1Fam          Y     962.0     830.0        0.0             3   
1356     1Fam          Y    1126.0       0.0        0.0             3   
1357     1Fam          Y    1537.0       0.0        0.0             3   
1358     1Fam          Y     864.0       0.0        0.0             3   
1359     1Fam          Y    1932.0       0.0      304.0             2   
1360     1Fam          Y    1236.0       0.0        0.0             2   
1361     1Fam          Y    1040.0     685.0        0.0             3   
1362     1Fam          Y    1423.0     748.0        0.0             3   
1363   TwnhsE          Y     848.0       0.0        0.0             1   
1364     1Fam          Y    1026.0     981.0        0.0             3   
1365     1Fam          N     952.0       0.0        0.0             2   
1366     1Fam          Y    1422.0       0.0        0.0             3   
1367     1Fam          Y     913.0       0.0        0.0             3   
1368     1Fam          Y    1188.0       0.0        0.0             3   
1369     1Fam          Y    1220.0     870.0        0.0             3   
1370     1Fam          N     796.0     550.0        0.0             2   
1371     1Fam          Y    1578.0       0.0        0.0        

In [3]:
df.head()

BldgType CentralAir  1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  \
0     1Fam          Y     856.0     854.0        0.0             3   
1     1Fam          Y    1262.0       0.0        0.0             3   
2     1Fam          Y     920.0     866.0        0.0             3   
3     1Fam          Y     961.0     756.0        0.0             3   
4     1Fam          Y    1145.0    1053.0        0.0             4   

   BsmtFinSF1  BsmtFinSF2  BsmtFullBath  BsmtHalfBath    ...      OverallQual  \
0       706.0         0.0             1             0    ...                7   
1       978.0         0.0             0             1    ...                6   
2       486.0         0.0             1             0    ...                7   
3       216.0         0.0             1             0    ...                7   
4       655.0         0.0             1             0    ...                8   

   PoolArea  ScreenPorch  TotRmsAbvGrd  TotalBsmtSF  WoodDeckSF  YearBuilt  \
0       0.0          0.0             8        856.0         0.0       2003   
1       0.0          0.0             6       1262.0       298.0       1976   
2       0.0          0.0             6        920.0         0.0       2001   
3       0.0          0.0             7        756.0         0.0       1915   
4       0.0          0.0             9       1145.0       192.0       2000   

   YearRemodAdd  YrSold  SalePrice  
0          2003    2008   208500.0  
1          1976    2007   181500.0  
2          2002    2008   223500.0  
3          1970    2006   140000.0  
4          2000    2008   250000.0  

[5 rows x 39 columns]

In [4]:
df.shape

(1379, 39)

In [5]:
df.columns

Index(['BldgType', 'CentralAir', '1stFlrSF', '2ndFlrSF', '3SsnPorch',
       'BedroomAbvGr', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath',
       'BsmtHalfBath', 'BsmtUnfSF', 'EnclosedPorch', 'Fireplaces', 'FullBath',
       'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath',
       'KitchenAbvGr', 'LotArea', 'LotFrontage', 'LowQualFinSF', 'MSSubClass',
       'MasVnrArea', 'MiscVal', 'MoSold', 'OpenPorchSF', 'OverallCond',
       'OverallQual', 'PoolArea', 'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF',
       'WoodDeckSF', 'YearBuilt', 'YearRemodAdd', 'YrSold', 'SalePrice'],
      dtype='object')

In [6]:
df.dtypes

BldgType          object
CentralAir        object
1stFlrSF         float64
2ndFlrSF         float64
3SsnPorch        float64
BedroomAbvGr       int64
BsmtFinSF1       float64
BsmtFinSF2       float64
BsmtFullBath       int64
BsmtHalfBath       int64
BsmtUnfSF        float64
EnclosedPorch    float64
Fireplaces         int64
FullBath           int64
GarageArea       float64
GarageCars         int64
GarageYrBlt      float64
GrLivArea        float64
HalfBath           int64
KitchenAbvGr       int64
LotArea          float64
LotFrontage      float64
LowQualFinSF     float64
MSSubClass         int64
MasVnrArea       float64
MiscVal          float64
MoSold             int64
OpenPorchSF      float64
OverallCond        int64
OverallQual        int64
PoolArea         float64
ScreenPorch      float64
TotRmsAbvGrd       int64
TotalBsmtSF      float64
WoodDeckSF       float64
YearBuilt          int64
YearRemodAdd       int64
YrSold             int64
SalePrice        float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 39 columns):
BldgType         1379 non-null object
CentralAir       1379 non-null object
1stFlrSF         1379 non-null float64
2ndFlrSF         1379 non-null float64
3SsnPorch        1379 non-null float64
BedroomAbvGr     1379 non-null int64
BsmtFinSF1       1379 non-null float64
BsmtFinSF2       1379 non-null float64
BsmtFullBath     1379 non-null int64
BsmtHalfBath     1379 non-null int64
BsmtUnfSF        1379 non-null float64
EnclosedPorch    1379 non-null float64
Fireplaces       1379 non-null int64
FullBath         1379 non-null int64
GarageArea       1379 non-null float64
GarageCars       1379 non-null int64
GarageYrBlt      1379 non-null float64
GrLivArea        1379 non-null float64
HalfBath         1379 non-null int64
KitchenAbvGr     1379 non-null int64
LotArea          1379 non-null float64
LotFrontage      1379 non-null float64
LowQualFinSF     1379 non-null float64
MSSubClass    

In [8]:
sr = pd.Series.from_csv('Ames_House_Sales_Cropped.csv')
sr.value_counts()

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\core\series.py:2890: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  infer_datetime_format=infer_datetime_format)


Y             1310
N               69
CentralAir       1
dtype: int64

In [9]:
dff=df.drop(["BldgType","CentralAir"],axis=1)
dff

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0        856.0     854.0        0.0             3       706.0         0.0   
1       1262.0       0.0        0.0             3       978.0         0.0   
2        920.0     866.0        0.0             3       486.0         0.0   
3        961.0     756.0        0.0             3       216.0         0.0   
4       1145.0    1053.0        0.0             4       655.0         0.0   
5        796.0     566.0      320.0             1       732.0         0.0   
6       1694.0       0.0        0.0             3      1369.0         0.0   
7       1107.0     983.0        0.0             3       859.0        32.0   
8       1022.0     752.0        0.0             2         0.0         0.0   
9       1077.0       0.0        0.0             2       851.0         0.0   
10      1040.0       0.0        0.0             3       906.0         0.0   
11      1182.0    1142.0        0.0             4       998.0         0.0   
12       912.0       0.0        0.0             2       737.0         0.0   
13      1494.0       0.0        0.0             3         0.0         0.0   
14      1253.0       0.0        0.0             2       733.0         0.0   
15       854.0       0.0        0.0             2         0.0         0.0   
16      1004.0       0.0        0.0             2       578.0         0.0   
17      1296.0       0.0        0.0             2         0.0         0.0   
18      1114.0       0.0        0.0             3       646.0         0.0   
19      1339.0       0.0        0.0             3       504.0         0.0   
20      1158.0    1218.0        0.0             4         0.0         0.0   
21      1108.0       0.0        0.0             3         0.0         0.0   
22      1795.0       0.0        0.0             3         0.0         0.0   
23      1060.0       0.0        0.0             3       840.0         0.0   
24      1060.0       0.0        0.0             3       188.0       668.0   
25      1600.0       0.0        0.0             3         0.0         0.0   
26       900.0       0.0        0.0             3       234.0       486.0   
27      1704.0       0.0        0.0             3      1218.0         0.0   
28      1600.0       0.0        0.0             2      1277.0         0.0   
29       520.0       0.0        0.0             1         0.0         0.0   
...        ...       ...        ...           ...         ...         ...   
1349    1048.0     510.0        0.0             3       580.0         0.0   
1350     804.0       0.0        0.0             2       510.0         0.0   
1351    1440.0       0.0        0.0             3       678.0         0.0   
1352     734.0    1104.0        0.0             4         0.0         0.0   
1353     958.0       0.0        0.0             2       958.0         0.0   
1354     968.0       0.0        0.0             4         0.0         0.0   
1355     962.0     830.0        0.0             3         0.0         0.0   
1356    1126.0       0.0        0.0             3       936.0         0.0   
1357    1537.0       0.0        0.0             3         0.0         0.0   
1358     864.0       0.0        0.0             3       616.0         0.0   
1359    1932.0       0.0      304.0             2      1336.0         0.0   
1360    1236.0       0.0        0.0             2       600.0         0.0   
1361    1040.0     685.0        0.0             3       315.0       110.0   
1362    1423.0     748.0        0.0             3         0.0         0.0   
1363     848.0       0.0        0.0             1       697.0         0.0   
1364    1026.0     981.0        0.0             3       765.0         0.0   
1365     952.0       0.0        0.0             2         0.0         0.0   
1366    1422.0       0.0        0.0             3         0.0         0.0   
1367     913.0       0.0        0.0             3       187.0       627.0   
1368    1188.0       0.0        0.0             3       593.0         0.0   
13

In [10]:
X=dff.drop(["SalePrice"],axis=1)
X

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0        856.0     854.0        0.0             3       706.0         0.0   
1       1262.0       0.0        0.0             3       978.0         0.0   
2        920.0     866.0        0.0             3       486.0         0.0   
3        961.0     756.0        0.0             3       216.0         0.0   
4       1145.0    1053.0        0.0             4       655.0         0.0   
5        796.0     566.0      320.0             1       732.0         0.0   
6       1694.0       0.0        0.0             3      1369.0         0.0   
7       1107.0     983.0        0.0             3       859.0        32.0   
8       1022.0     752.0        0.0             2         0.0         0.0   
9       1077.0       0.0        0.0             2       851.0         0.0   
10      1040.0       0.0        0.0             3       906.0         0.0   
11      1182.0    1142.0        0.0             4       998.0         0.0   
12       912.0       0.0        0.0             2       737.0         0.0   
13      1494.0       0.0        0.0             3         0.0         0.0   
14      1253.0       0.0        0.0             2       733.0         0.0   
15       854.0       0.0        0.0             2         0.0         0.0   
16      1004.0       0.0        0.0             2       578.0         0.0   
17      1296.0       0.0        0.0             2         0.0         0.0   
18      1114.0       0.0        0.0             3       646.0         0.0   
19      1339.0       0.0        0.0             3       504.0         0.0   
20      1158.0    1218.0        0.0             4         0.0         0.0   
21      1108.0       0.0        0.0             3         0.0         0.0   
22      1795.0       0.0        0.0             3         0.0         0.0   
23      1060.0       0.0        0.0             3       840.0         0.0   
24      1060.0       0.0        0.0             3       188.0       668.0   
25      1600.0       0.0        0.0             3         0.0         0.0   
26       900.0       0.0        0.0             3       234.0       486.0   
27      1704.0       0.0        0.0             3      1218.0         0.0   
28      1600.0       0.0        0.0             2      1277.0         0.0   
29       520.0       0.0        0.0             1         0.0         0.0   
...        ...       ...        ...           ...         ...         ...   
1349    1048.0     510.0        0.0             3       580.0         0.0   
1350     804.0       0.0        0.0             2       510.0         0.0   
1351    1440.0       0.0        0.0             3       678.0         0.0   
1352     734.0    1104.0        0.0             4         0.0         0.0   
1353     958.0       0.0        0.0             2       958.0         0.0   
1354     968.0       0.0        0.0             4         0.0         0.0   
1355     962.0     830.0        0.0             3         0.0         0.0   
1356    1126.0       0.0        0.0             3       936.0         0.0   
1357    1537.0       0.0        0.0             3         0.0         0.0   
1358     864.0       0.0        0.0             3       616.0         0.0   
1359    1932.0       0.0      304.0             2      1336.0         0.0   
1360    1236.0       0.0        0.0             2       600.0         0.0   
1361    1040.0     685.0        0.0             3       315.0       110.0   
1362    1423.0     748.0        0.0             3         0.0         0.0   
1363     848.0       0.0        0.0             1       697.0         0.0   
1364    1026.0     981.0        0.0             3       765.0         0.0   
1365     952.0       0.0        0.0             2         0.0         0.0   
1366    1422.0       0.0        0.0             3         0.0         0.0   
1367     913.0       0.0        0.0             3       187.0       627.0   
1368    1188.0       0.0        0.0             3       593.0         0.0   
13

In [11]:
X

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0        856.0     854.0        0.0             3       706.0         0.0   
1       1262.0       0.0        0.0             3       978.0         0.0   
2        920.0     866.0        0.0             3       486.0         0.0   
3        961.0     756.0        0.0             3       216.0         0.0   
4       1145.0    1053.0        0.0             4       655.0         0.0   
5        796.0     566.0      320.0             1       732.0         0.0   
6       1694.0       0.0        0.0             3      1369.0         0.0   
7       1107.0     983.0        0.0             3       859.0        32.0   
8       1022.0     752.0        0.0             2         0.0         0.0   
9       1077.0       0.0        0.0             2       851.0         0.0   
10      1040.0       0.0        0.0             3       906.0         0.0   
11      1182.0    1142.0        0.0             4       998.0         0.0   
12       912.0       0.0        0.0             2       737.0         0.0   
13      1494.0       0.0        0.0             3         0.0         0.0   
14      1253.0       0.0        0.0             2       733.0         0.0   
15       854.0       0.0        0.0             2         0.0         0.0   
16      1004.0       0.0        0.0             2       578.0         0.0   
17      1296.0       0.0        0.0             2         0.0         0.0   
18      1114.0       0.0        0.0             3       646.0         0.0   
19      1339.0       0.0        0.0             3       504.0         0.0   
20      1158.0    1218.0        0.0             4         0.0         0.0   
21      1108.0       0.0        0.0             3         0.0         0.0   
22      1795.0       0.0        0.0             3         0.0         0.0   
23      1060.0       0.0        0.0             3       840.0         0.0   
24      1060.0       0.0        0.0             3       188.0       668.0   
25      1600.0       0.0        0.0             3         0.0         0.0   
26       900.0       0.0        0.0             3       234.0       486.0   
27      1704.0       0.0        0.0             3      1218.0         0.0   
28      1600.0       0.0        0.0             2      1277.0         0.0   
29       520.0       0.0        0.0             1         0.0         0.0   
...        ...       ...        ...           ...         ...         ...   
1349    1048.0     510.0        0.0             3       580.0         0.0   
1350     804.0       0.0        0.0             2       510.0         0.0   
1351    1440.0       0.0        0.0             3       678.0         0.0   
1352     734.0    1104.0        0.0             4         0.0         0.0   
1353     958.0       0.0        0.0             2       958.0         0.0   
1354     968.0       0.0        0.0             4         0.0         0.0   
1355     962.0     830.0        0.0             3         0.0         0.0   
1356    1126.0       0.0        0.0             3       936.0         0.0   
1357    1537.0       0.0        0.0             3         0.0         0.0   
1358     864.0       0.0        0.0             3       616.0         0.0   
1359    1932.0       0.0      304.0             2      1336.0         0.0   
1360    1236.0       0.0        0.0             2       600.0         0.0   
1361    1040.0     685.0        0.0             3       315.0       110.0   
1362    1423.0     748.0        0.0             3         0.0         0.0   
1363     848.0       0.0        0.0             1       697.0         0.0   
1364    1026.0     981.0        0.0             3       765.0         0.0   
1365     952.0       0.0        0.0             2         0.0         0.0   
1366    1422.0       0.0        0.0             3         0.0         0.0   
1367     913.0       0.0        0.0             3       187.0       627.0   
1368    1188.0       0.0        0.0             3       593.0         0.0   
13

In [12]:
y=dff["SalePrice"].values
y

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
y_pred=reg.predict(X_test)
y_pred

array([257434.93050745, 111083.7347476 , 100018.05832303, 204028.53821314,
       207319.25418312,  38036.30928932, 234153.38582868, 205076.12689608,
       187014.1265524 , 235636.78799031, 100976.50943769, 304119.53646983,
       101769.64600713, 288758.46001593, 204767.89338328, 145002.47279616,
       248322.97436852, 151533.68038634, 209697.39458712, 278312.23574148,
        93329.85601474, 153784.14868375, 163237.87451138, 241495.9121289 ,
       372429.94726945, 221672.07367609, 119658.75685737, 100039.78137073,
       319435.0289208 , 172088.64665031, 258772.64470117, 199597.36129642,
       156349.69283212, 142311.22500101, 204807.33161321, 379608.17785443,
       124176.23377551, 141127.25006141, 273832.43247645, 212547.04205553,
       169474.57176142, 123305.65719311, 200341.24016791, 377957.32307114,
       146941.7171239 , 283693.48760668, 106694.19786718, 221733.02172508,
        87733.47014004, 295005.66546305, 125250.62019285,  53569.11256022,
       133831.0508612 , 1

In [16]:
import sklearn.metrics as metrics
mse=metrics.mean_squared_error(y_test,y_pred)
print("MSE without Categorical: ",mse)

MSE without Categorical:  1474827325.5975406


In [17]:
import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred)
plt.xlabel("y_test")
plt.ylabel("y_pred")
plt.title("Plot b/w y_test vs y_pred")
plt.show()

In [18]:
encode=pd.get_dummies(df)
encode

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0        856.0     854.0        0.0             3       706.0         0.0   
1       1262.0       0.0        0.0             3       978.0         0.0   
2        920.0     866.0        0.0             3       486.0         0.0   
3        961.0     756.0        0.0             3       216.0         0.0   
4       1145.0    1053.0        0.0             4       655.0         0.0   
5        796.0     566.0      320.0             1       732.0         0.0   
6       1694.0       0.0        0.0             3      1369.0         0.0   
7       1107.0     983.0        0.0             3       859.0        32.0   
8       1022.0     752.0        0.0             2         0.0         0.0   
9       1077.0       0.0        0.0             2       851.0         0.0   
10      1040.0       0.0        0.0             3       906.0         0.0   
11      1182.0    1142.0        0.0             4       998.0         0.0   
12       912.0       0.0        0.0             2       737.0         0.0   
13      1494.0       0.0        0.0             3         0.0         0.0   
14      1253.0       0.0        0.0             2       733.0         0.0   
15       854.0       0.0        0.0             2         0.0         0.0   
16      1004.0       0.0        0.0             2       578.0         0.0   
17      1296.0       0.0        0.0             2         0.0         0.0   
18      1114.0       0.0        0.0             3       646.0         0.0   
19      1339.0       0.0        0.0             3       504.0         0.0   
20      1158.0    1218.0        0.0             4         0.0         0.0   
21      1108.0       0.0        0.0             3         0.0         0.0   
22      1795.0       0.0        0.0             3         0.0         0.0   
23      1060.0       0.0        0.0             3       840.0         0.0   
24      1060.0       0.0        0.0             3       188.0       668.0   
25      1600.0       0.0        0.0             3         0.0         0.0   
26       900.0       0.0        0.0             3       234.0       486.0   
27      1704.0       0.0        0.0             3      1218.0         0.0   
28      1600.0       0.0        0.0             2      1277.0         0.0   
29       520.0       0.0        0.0             1         0.0         0.0   
...        ...       ...        ...           ...         ...         ...   
1349    1048.0     510.0        0.0             3       580.0         0.0   
1350     804.0       0.0        0.0             2       510.0         0.0   
1351    1440.0       0.0        0.0             3       678.0         0.0   
1352     734.0    1104.0        0.0             4         0.0         0.0   
1353     958.0       0.0        0.0             2       958.0         0.0   
1354     968.0       0.0        0.0             4         0.0         0.0   
1355     962.0     830.0        0.0             3         0.0         0.0   
1356    1126.0       0.0        0.0             3       936.0         0.0   
1357    1537.0       0.0        0.0             3         0.0         0.0   
1358     864.0       0.0        0.0             3       616.0         0.0   
1359    1932.0       0.0      304.0             2      1336.0         0.0   
1360    1236.0       0.0        0.0             2       600.0         0.0   
1361    1040.0     685.0        0.0             3       315.0       110.0   
1362    1423.0     748.0        0.0             3         0.0         0.0   
1363     848.0       0.0        0.0             1       697.0         0.0   
1364    1026.0     981.0        0.0             3       765.0         0.0   
1365     952.0       0.0        0.0             2         0.0         0.0   
1366    1422.0       0.0        0.0             3         0.0         0.0   
1367     913.0       0.0        0.0             3       187.0       627.0   
1368    1188.0       0.0        0.0             3       593.0         0.0   
13

In [19]:
X=encode.drop(["SalePrice"],axis=1)
X

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0        856.0     854.0        0.0             3       706.0         0.0   
1       1262.0       0.0        0.0             3       978.0         0.0   
2        920.0     866.0        0.0             3       486.0         0.0   
3        961.0     756.0        0.0             3       216.0         0.0   
4       1145.0    1053.0        0.0             4       655.0         0.0   
5        796.0     566.0      320.0             1       732.0         0.0   
6       1694.0       0.0        0.0             3      1369.0         0.0   
7       1107.0     983.0        0.0             3       859.0        32.0   
8       1022.0     752.0        0.0             2         0.0         0.0   
9       1077.0       0.0        0.0             2       851.0         0.0   
10      1040.0       0.0        0.0             3       906.0         0.0   
11      1182.0    1142.0        0.0             4       998.0         0.0   
12       912.0       0.0        0.0             2       737.0         0.0   
13      1494.0       0.0        0.0             3         0.0         0.0   
14      1253.0       0.0        0.0             2       733.0         0.0   
15       854.0       0.0        0.0             2         0.0         0.0   
16      1004.0       0.0        0.0             2       578.0         0.0   
17      1296.0       0.0        0.0             2         0.0         0.0   
18      1114.0       0.0        0.0             3       646.0         0.0   
19      1339.0       0.0        0.0             3       504.0         0.0   
20      1158.0    1218.0        0.0             4         0.0         0.0   
21      1108.0       0.0        0.0             3         0.0         0.0   
22      1795.0       0.0        0.0             3         0.0         0.0   
23      1060.0       0.0        0.0             3       840.0         0.0   
24      1060.0       0.0        0.0             3       188.0       668.0   
25      1600.0       0.0        0.0             3         0.0         0.0   
26       900.0       0.0        0.0             3       234.0       486.0   
27      1704.0       0.0        0.0             3      1218.0         0.0   
28      1600.0       0.0        0.0             2      1277.0         0.0   
29       520.0       0.0        0.0             1         0.0         0.0   
...        ...       ...        ...           ...         ...         ...   
1349    1048.0     510.0        0.0             3       580.0         0.0   
1350     804.0       0.0        0.0             2       510.0         0.0   
1351    1440.0       0.0        0.0             3       678.0         0.0   
1352     734.0    1104.0        0.0             4         0.0         0.0   
1353     958.0       0.0        0.0             2       958.0         0.0   
1354     968.0       0.0        0.0             4         0.0         0.0   
1355     962.0     830.0        0.0             3         0.0         0.0   
1356    1126.0       0.0        0.0             3       936.0         0.0   
1357    1537.0       0.0        0.0             3         0.0         0.0   
1358     864.0       0.0        0.0             3       616.0         0.0   
1359    1932.0       0.0      304.0             2      1336.0         0.0   
1360    1236.0       0.0        0.0             2       600.0         0.0   
1361    1040.0     685.0        0.0             3       315.0       110.0   
1362    1423.0     748.0        0.0             3         0.0         0.0   
1363     848.0       0.0        0.0             1       697.0         0.0   
1364    1026.0     981.0        0.0             3       765.0         0.0   
1365     952.0       0.0        0.0             2         0.0         0.0   
1366    1422.0       0.0        0.0             3         0.0         0.0   
1367     913.0       0.0        0.0             3       187.0       627.0   
1368    1188.0       0.0        0.0             3       593.0         0.0   
13

In [20]:
y=encode["SalePrice"].values
y

array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=42)

In [22]:
from sklearn.linear_model import LinearRegression

reg=LinearRegression()
reg.fit(X_train,y_train)
y_pred=reg.predict(X_test)
y


array([208500., 181500., 223500., ..., 266500., 142125., 147500.])

In [23]:
import sklearn.metrics as metrics
mse_cd=metrics.mean_squared_error(y_test,y_pred)
print("MSE with Categorical data: ",mse_cd)

MSE with Categorical data:  1461036570.1436336


In [24]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
std_X_train=std.fit_transform(X_train)
std_X_train

array([[ 0.39851037, -0.79290427, -0.11340519, ...,  3.45325933,
        -0.22777619,  0.22777619],
       [ 1.57467708, -0.79290427, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [ 0.37564751,  0.70143387, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       ...,
       [ 1.22157303, -0.79290427, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [-1.11297817,  0.90510323, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [ 0.11145456, -0.79290427, -0.11340519, ...,  3.45325933,
        -0.22777619,  0.22777619]])

In [25]:
std_X_test=std.transform(X_test)
std_X_test

array([[ 0.85830772, -0.79290427, -0.11340519, ...,  3.45325933,
        -0.22777619,  0.22777619],
       [-0.64810018, -0.79290427, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [-0.21624632,  0.76093278, -0.11340519, ..., -0.2895815 ,
         4.39027446, -4.39027446],
       ...,
       [-0.04350477,  0.37647826, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [-0.64301955,  1.46805451, -0.11340519, ..., -0.2895815 ,
        -0.22777619,  0.22777619],
       [-0.29499614,  0.81585486, -0.11340519, ...,  3.45325933,
        -0.22777619,  0.22777619]])

In [26]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(std_X_train,y_train)
std_y_pred=lr.predict(std_X_test)
std_y_pred

array([257746.67634751, 113257.14215097,  83086.83449793, 204109.44696503,
       209062.51895279,  69091.78945845, 235181.17333175, 205722.26326666,
       187627.82768487, 234276.07879635, 101443.5208025 , 304189.5355825 ,
       102111.08803612, 289185.34424259, 204499.21833429, 142096.29751997,
       249636.03306251, 147881.8828702 , 210574.13858086, 277457.62922997,
        91416.02948336, 153937.03347396, 160626.96732406, 243147.94924865,
       372541.07042985, 219861.59417986, 116849.37194182, 100880.38852652,
       318604.3072889 , 168091.93524469, 258085.96044038, 201316.99711925,
       154599.59088249, 142746.1064703 , 205138.6701111 , 382254.53304499,
       124930.2956851 , 141597.13070899, 273664.48982728, 214149.35804835,
       170457.21544846, 124570.77597839, 197619.98987752, 376155.99238854,
       148003.84323244, 288043.80788135, 108672.5169885 , 218565.03839169,
        88455.07127747, 295191.90839717, 125798.92162385,  54900.46063498,
       133431.33010679, 1

In [27]:
std_mse=metrics.mean_squared_error(y_test,std_y_pred)
print("Mean Squared Error: ",std_mse)

Mean Squared Error:  1461036570.1437433


In [28]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
mm_X_train=mm.fit_transform(X_train)
mm_X_test=mm.transform(X_test)

reg.fit(mm_X_train,y_train)
mm_y_pred=reg.predict(mm_X_test)
mm_y_pred

array([257746.67634751, 113257.14215097,  83086.83449793, 204109.44696503,
       209062.51895279,  69091.78945845, 235181.17333175, 205722.26326666,
       187627.82768487, 234276.07879635, 101443.5208025 , 304189.5355825 ,
       102111.08803612, 289185.34424259, 204499.21833429, 142096.29751997,
       249636.03306251, 147881.8828702 , 210574.13858086, 277457.62922997,
        91416.02948336, 153937.03347396, 160626.96732406, 243147.94924865,
       372541.07042985, 219861.59417986, 116849.37194182, 100880.38852652,
       318604.3072889 , 168091.93524469, 258085.96044038, 201316.99711925,
       154599.59088249, 142746.1064703 , 205138.6701111 , 382254.53304499,
       124930.2956851 , 141597.13070899, 273664.48982728, 214149.35804835,
       170457.21544846, 124570.77597839, 197619.98987752, 376155.99238854,
       148003.84323244, 288043.80788135, 108672.5169885 , 218565.03839169,
        88455.07127747, 295191.90839717, 125798.92162385,  54900.46063498,
       133431.33010679, 1

In [29]:
mm_mse=metrics.mean_squared_error(y_test,mm_y_pred)
print("Mean Squared Error: ",mm_mse)

Mean Squared Error:  1461036570.1437414


In [30]:
from sklearn.linear_model import SGDRegressor
sgd=SGDRegressor()
sgd.fit(std_X_train, y_train)
sgd_y_pred=sgd.predict(std_X_test)
sgd_y_pred

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


array([259147.70351588, 102092.90636032, 109562.72080809, 206188.90815394,
       207199.0326119 ,  62673.97585799, 238353.83964253, 207516.26231648,
       186618.21560342, 230489.45011426,  95496.47350095, 311485.50026731,
        97261.56500481, 295987.2342127 , 207807.53567472, 146162.82056379,
       249267.15564966, 150228.39096521, 210174.6051096 , 285315.68885581,
        93013.32026423, 148297.55074549, 161026.56314257, 247100.21358829,
       383894.69558586, 226893.43332889, 119271.91587749,  90705.62791612,
       333937.69440651, 169867.37296667, 264524.02267823, 201015.10137058,
       153153.26723448, 132035.9654406 , 204886.10122395, 387877.29292617,
       109465.59695717, 139814.36851979, 279846.89102327, 206148.07428302,
       167746.4531547 , 117189.05941449, 190028.70347537, 375151.31085743,
       151275.5873011 , 298006.88457661,  95941.34056363, 224849.11308558,
        82886.48842265, 303871.07158172, 120199.03423161,  39949.90806642,
       135738.04706132, 1

In [31]:
sgd_mse=metrics.mean_squared_error(y_test, sgd_y_pred)
print("Mean Squared Error:",sgd_mse)

Mean Squared Error: 1515187705.7597847


In [32]:
from sklearn.linear_model import Ridge
ridge=Ridge()
ridge.fit(std_X_train, y_train)
ridge_y_pred=ridge.predict(std_X_test)
ridge_y_pred

array([257716.40699318, 113188.83783395,  83441.68622524, 204093.86685461,
       209046.77119427,  68968.95970424, 235166.85073532, 205709.18701907,
       187608.88092307, 234127.91986613, 101442.61753652, 303996.83085985,
       102207.81104997, 289201.83025972, 204530.52882459, 142227.09469735,
       249528.85892308, 147950.18211509, 210586.82424173, 277366.73836724,
        91543.67482183, 153978.54592712, 160695.6139235 , 243057.53405206,
       372495.11731184, 219840.91884082, 116956.95574687, 100878.46795325,
       318603.53970706, 168136.34840742, 258058.73912129, 201180.97018482,
       154470.04859036, 142707.68415143, 205133.17128488, 382062.98759242,
       124795.49109482, 141435.74207829, 273560.58911851, 214075.03676925,
       170494.5832031 , 124523.92339387, 197429.91336254, 375822.0370805 ,
       148108.22483297, 288075.31154386, 108608.62662542, 218573.47618249,
        88587.3998216 , 295171.57452763, 125737.07110059,  54833.67931716,
       133481.71022526, 1

In [33]:
ridge_mse=metrics.mean_squared_error(y_test, ridge_y_pred)
print("RIDGE Mean Squared Error:",ridge_mse)

RIDGE Mean Squared Error: 1458946958.0904446


In [34]:
from sklearn.linear_model import Lasso
lasso=Lasso()
lasso.fit(std_X_train, y_train)
lasso_y_pred=lasso.predict(std_X_test)
lasso_y_pred

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


array([257729.69686228, 113247.68204486,  83142.29454527, 204106.43998851,
       209066.49021888,  69054.81228022, 235176.11930442, 205711.84838767,
       187608.59515698, 234284.06084395, 101449.25460271, 304193.6360213 ,
       102109.0711376 , 289198.43257911, 204491.12189758, 142122.85239194,
       249633.03850946, 147889.3873303 , 210566.82234788, 277458.74148889,
        91422.16023407, 153936.54170005, 160629.24135716, 243131.57205681,
       372542.62040315, 219872.31056047, 116863.87010022, 100885.24049767,
       318608.68254302, 168098.13679091, 258090.97848895, 201288.31490053,
       154603.02948577, 142756.31460187, 205137.22911272, 382237.47687556,
       124919.66167664, 141572.72803651, 273666.16449995, 214125.2076817 ,
       170460.20631671, 124565.97224865, 197629.92077736, 376132.94977617,
       148005.53413165, 288031.84338491, 108663.12260663, 218568.08286906,
        88451.65003835, 295193.48660115, 125792.5796616 ,  54906.97302469,
       133434.7793381 , 1

In [35]:
lasso_mse=metrics.mean_squared_error(y_test, lasso_y_pred)
print("LASSO Mean Squared Error:",lasso_mse)

LASSO Mean Squared Error: 1460906418.115903


In [36]:
import numpy as np

In [37]:
np.sqrt(mse)

38403.48064430541

In [38]:
np.sqrt(mse_cd)

38223.50808263985

In [39]:
np.sqrt(std_mse)

38223.50808264128

In [40]:
np.sqrt(mm_mse)

38223.50808264125

In [41]:
np.sqrt(sgd_mse)

38925.41208208058

In [42]:
np.sqrt(ridge_mse)

38196.164180326334

In [43]:
np.sqrt(lasso_mse)

38221.805531867576